### ISSUE TITLE
Unexpected server response

### ISSUE THREAD

**Issue by jaxenX** [GeniusXD/free-agario-fb-bots#13]
Hi
I am getting this error;
```
Error: Unexpected server response: 503
    at ClientRequest.<anonymous> (C:\Users\jaxen\Downloads\free-agario-fb-bots-master\free-agario-fb-bots-master\node_modules\ws\lib\websocket.js:579:7)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by ArvdSrh** [comment]
Bots are patched I think, even if its not, this project is discontinued.
